---
version: '3.4'

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile-builder
      args:
        - GROUP_ID
        - USER_ID
        - WORKDIR
    command: tail -f /dev/null
    environment:
        - DESCRIBE
    stdin_open: true
    tty: true
    volumes:
      - .:${WORKDIR}
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    stdin_open: true
    tty: true
    user: ${USER_ID}:${GROUP_ID}
