---
version: '3.4'

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile-builder
      args:
        - GROUP_ID
        - USER_ID
        - WORKDIR
    command: tail -f /dev/null
    tty: true
    stdin_open: true
    volumes:
      - .:${WORKDIR}
